//
//  Profil Musisi.swift
//  My Favorite Musician
//
//  Created by Fikri on 19/05/20.
//  Copyright © 2020 Fikri Helmi. All rights reserved.
//

import UIKit

var profilMusisi: [Musisi] = [
    
    Musisi(nama: "Ardhito Pramono", foto: UIImage(named: "Ardhito Pramono")!, deskripsi: "Ardhito Rifqi Pramono yang akrab dipanggil Ardhito (lahir di Jakarta, 22 Mei 1995; umur 24 tahun) adalah seorang penyanyi, penulis lagu dan pemeran asal Indonesia. Selain seorang penyanyi, Ardhito pernah menjadi seorang creative planner dan juga music director. Ia juga pernah terlibat dengan penggarapan sebuah short film dan web-series.", namaAsli: "Ardhito Rifqi Pramono", TTL: "Tempat, Tanggal Lahir",  isiTTL: "Jakarta, 22 Mei 1995", genre: "Genre", isiGenre: "Pop, Jazz", song1: "Bila", song2: "Fine Today", song3: "925", fotoSong1: UIImage(named: "Ardhito Song 3")!, fotoSong2: UIImage(named: "Ardhito Song 3")!, fotoSong3: UIImage(named: "Ardhito Song 3")!),
    Musisi(nama: "Hindia", foto: UIImage(named: "Hindia")!, deskripsi : "Daniel Baskara Putra (lahir di Jakarta, 22 Februari 1994; umur 26 tahun) adalah penyanyi dan penulis lagu asal Indonesia. Ia adalah vokalis grup musik .Feast namun juga merilis musik solo dengan moniker Hindia.", namaAsli: "Daniel Baskara Putra",  TTL: "Tempat, Tanggal Lahir", isiTTL: "Jakarta, 22 Februari 1994", genre: "Genre", isiGenre: "Pop, Alternative Rock", song1: "Secukupnya", song2: "Evakuasi", song3: "Membasuh", fotoSong1: UIImage(named: "Hindia Song 2")!, fotoSong2: UIImage(named: "Hindia Song 2")!, fotoSong3: UIImage(named: "Hindia Song 2")!),
    Musisi(nama: "Kunto Aji", foto: UIImage(named: "Kunto Aji")!, deskripsi : "Kunto Aji Wibisono (lahir di Yogyakarta, 04 Januari 1987; umur 33 tahun) adalah seorang penyanyi berkebangsaan Indonesia. Ia melejit lewat acara pencarian bakat Indonesian Idol musim kelima. Aji menjadi finalis keempat pada ajang itu. Pada tahun 2010, ia mencoba merambah ke dunia layar kaca dengan membintangi film pertamanya \"Senggol Bacok\". Penyanyi kelahiran Yogyakarta ini, memulai debut singlenya yaitu Terlalu Lama Sendiri pada tahun 2014.", namaAsli: "Kunto Aji Wibisono", TTL: "Tempat, Tanggal Lahir",  isiTTL: "Yogya, 04 Januari 1987", genre: "Genre", isiGenre: "Pop, Jazz", song1: "Rehat", song2: "Pilu Membiru", song3: "Sulung", fotoSong1: UIImage(named: "Kunto Aji Song 2")!, fotoSong2: UIImage(named: "Kunto Aji Song 2")!, fotoSong3: UIImage(named: "Kunto Aji Song 2")!),
    Musisi(nama: "Fiersa Besari", foto: UIImage(named: "Fiersa Besari")!, deskripsi : "Fiersa Besari (lahir di Bandung, 3 Maret 1984; umur 36 tahun) adalah penulis dan pemusik Indonesia. Sebagai penulis, Fiersa telah menghasilkan enam novel. Ia juga terlibat sebagai salah satu pendiri Komunitas Pecandu Buku.", namaAsli: "Fiersa Besari", TTL: "Tempat, Tanggal Lahir", isiTTL: "Bandung, 3 Maret 1984", genre: "Genre", isiGenre: "Pop, Balada", song1: "Waktu Yang Salah", song2: "Celengan Rindu", song3: "Pelukku Untuk Pelikmu", fotoSong1: UIImage(named: "Fiersa Besari Song 2")!, fotoSong2: UIImage(named: "Fiersa Besari Song 2")!, fotoSong3: UIImage(named: "Fiersa Besari Song 3")!),
    Musisi(nama: "Fourtwenty", foto: UIImage(named: "Fourtwenty")!, deskripsi : "Fourtwnty adalah grup musik indie asal Indonesia. Grup ini beranggotakan Ari Lesmana, Nuwi dan Roots ini turut dibentuk oleh Roby Satria, yang juga merupakan personel Geisha.", namaAsli: "Ari Lesmana (Vokalis)",  TTL: "Tempat, Tanggal Lahir",  isiTTL: "23 Tahun (Ari Lesmana)", genre: "Genre", isiGenre: "Folk", song1: "Zona Nyaman", song2: "Fana Merah Jambu", song3: "Kita Pasti Tua", fotoSong1: UIImage(named: "Fourtwenty Song 1")!, fotoSong2: UIImage(named: "Fourtwenty Song 1")!, fotoSong3: UIImage(named: "Fourtwenty Song 1")!),
    Musisi(nama: "Alan Walker", foto: UIImage(named: "Alan Walker")!, deskripsi : "Alan Olav Walker (lahir 24 Agustus 1997) adalah produser rekaman dan DJ berkebangsaan Norwegia-Inggris. Ia dikenal karena single \"Faded\", dengan menerima sertifikasi platinum lebih dari 10 negara yang berbeda. Alan Walker menempati peringkat 36 dalam DJ Mag's Top 100 DJs list of 2018, menempati 19 posisi lebih rendah dibandingkan tahun sebelumnya.", namaAsli: "Alan Olav Walker", TTL: "Tempat, Tanggal Lahir", isiTTL: "Norwegia, 24 Agustus 1997", genre: "Genre", isiGenre: "EDM", song1: "Different World", song2: "Diamond Heart", song3: "Lily", fotoSong1: UIImage(named: "Alan Walker Song 1")!, fotoSong2: UIImage(named: "Alan Walker Song 2")!, fotoSong3: UIImage(named: "Alan Walker Song 3")!),
    Musisi(nama: "Rich Brian", foto: UIImage(named: "Rich Brian")!, deskripsi : "Brian Imanuel Soewarno (lahir di Jakarta, Indonesia, 3 September 1999; umur 20 tahun), yang lebih dikenal dengan nama panggung Rich Brian (sebelumnya Rich Chigga), adalah seorang penyanyi rap, produser rekaman, dan penulis lagu dari Indonesia. Ia dikenal melalui singelnya yang bertajuk \"Dat $tick\", yang dirilis pada bulan Maret 2016.", namaAsli: "Brian Imanuel", TTL: "Tempat, Tanggal Lahir", isiTTL: "Jakarta, 3 September 1999", genre: "Genre", isiGenre: "Hip-Hop", song1: "Cold", song2: "Kids", song3: "The Sailor", fotoSong1: UIImage(named: "Rich Brian Song 2")!, fotoSong2: UIImage(named: "Rich Brian Song 2")!, fotoSong3: UIImage(named: "Rich Brian Song 2")!),
    Musisi(nama: "Marshmello", foto: UIImage(named: "Marshmello")!, deskripsi : "Christopher Comstock, (lahir 19 Mei 1992) yang biasa dikenal dengan Marshmello, adalah seorang produser musik dan disjoki musik dansa elektronik asal Amerika Serikat. Dia pertama kali mendapat pengakuan internasional dengan mendaur ulang lagu-lagu Jack Ü dan Zedd.", namaAsli: "Christopher Comstock",  TTL: "Tempat, Tanggal Lahir",  isiTTL: "USA, 19 Mei 1992", genre: "Genre", isiGenre: "Electronic", song1: "Happier", song2: "Here With Me", song3: "Friends", fotoSong1: UIImage(named: "Marshmello Song 2")!, fotoSong2: UIImage(named: "Marshmello Song 2")!, fotoSong3: UIImage(named: "Marshmello Song 2")!),
    Musisi(nama: "Danilla Riyadi", foto: UIImage(named: "Danilla Riyadi")!, deskripsi : "Danilla Riyadi (lahir 12 Februari 1990; umur 30 tahun) merupakan seorang penyanyi dan aktris Indonesia. Darah musik memang mengalir pada wanita yang enggan dijuluki soloist, musisi, penyanyi dan sebagainya dengan nama lengkap Danilla Jelita Poetri Riyadi. Ibunya adalah penyanyi Ika Ratih Poespa, dua pamannya bernama Dian Pramana Poetra dan Henry Restoe Poetra serta neneknya, Sumiati Sutiko, menyanyi keroncong pada dekade \"60-an.", namaAsli: "Danilla Riyadi",  TTL: "Tempat, Tanggal Lahir",  isiTTL: "12 Februari 1990", genre: "Genre", isiGenre: "Pop", song1: "Senja Diambang Pilu", song2: "Ada Di Sana", song3: "Batas", fotoSong1: UIImage(named: "Danilla Riyadi Song 1")!, fotoSong2: UIImage(named: "Danilla Riyadi Song 1")!, fotoSong3: UIImage(named: "Danilla Riyadi Song 1")!),
    Musisi(nama: "Sungha Jung", foto: UIImage(named: "Sungha Jung")!, deskripsi : "Sungha Jung adalah musisi Korea Selatan yang berspesialisasi dalam gitar akustik jari. Jung membuat sampul dan pengaturan akustik, biasanya dengan telinga dan / atau dengan menonton video, dan membuat lagu-lagu asli, yang ia putar dan unggah secara online.", namaAsli: "Seongha Jeong (정성하)",  TTL: "Tempat, Tanggal Lahir", isiTTL: "Korsel, 2 September 1996", genre: "Genre", isiGenre: "Instrument, Fingerstyle", song1: "L'atelier", song2: "Sunset In Paris", song3: "The Milky Way", fotoSong1: UIImage(named: "Sungha Jung Song 3")!, fotoSong2: UIImage(named: "Sungha Jung Song 3")!, fotoSong3: UIImage(named: "Sungha Jung Song 3")!)
        
]

